#!/bin/bash
wget -q https://raw.githubusercontent.com/smptxxx/scnexus/main/Fls/http -O /usr/bin/http
cekhttp=$(cat /usr/bin/http)


#install
apt update && apt upgrade
apt install neofetch -y
apt install python3 python3-pip git
clear
neofetch
echo -e "  \e[92;1m Information System \e[0m"
echo -e "  \e[97;1m---------------------------------------"
echo -e "  \e[97;1m              SCRIPT TUNNEL              "
echo -e "  \e[97;1m---------------------------------------"
echo -e ""
